### ISSUE TITLE
Engine-BaselineValidator-M365-SPO.ps1 error

### ISSUE THREAD

**Issue by sympmarc** [tmaestrini/easyGovernance#1]
I know you just started this effort, but I'm really intrigued! It doesn't look like there's anything working yet? I've cloned it and I get stuck on line 6 of Engine-BaselineValidator-M365-SPO.ps1

![image](https://github.com/tmaestrini/easyGovernance/assets/1295627/a23cf24f-38e1-4c3e-b6e5-e3625525c231)

I expect there's a prerequisite for yaml processing...

Before I try much more, I just figured I'd check in.

**Comment by tmaestrini** [comment]
Hey @sympmarc, so glad to read that you're interested in or project! 😍 welcome!
As we've started some days ago, I haven't prepared anything so far.
Therefore, the README is missing the following two dependencies:

Install-Module -Name powershell-yaml -Scope CurrentUser
Install-Module -Name PnP.PowerShell -RequiredVersion 2.2.0 -Scope CurrentUser

Tell me if it's working. It's still work in progress, I will check the preable in as soon as I am at home. 🙌

**Comment by sympmarc** [comment]
I figured out the poweshell-yaml dependency. Bravo me!

I'm running an older version PnP.PowerShell (1.12) because of some client needs. I'll try the newer version.

But I also think you've got some shortcut logic in the PowerShell that doesn't quite work. I'd suggest spelling out all the shortcuts. For example, VS Code thinks `?` means `Where-Object`, but that doesn't work. In VS Code, I get the problems in the screenshot below. Some are meaningful, but others not so much.

![image](https://github.com/tmaestrini/easyGovernance/assets/1295627/b0e0c65a-93de-4679-b060-445ca5ce8f08)

Once I understand a little more about what you're doing, I'm hoping I can contribute!

**Comment by tmaestrini** [comment]
Hmmm, are you on PowerShell 5.1 or >=7?
I also will add a .devcontainer, so you don't need to install the modules locally.

**Comment by sympmarc** [comment]
Doh! You're right: I was on PowerShell 5.1 - also for client reasons.

I still say you should expand things like `Select`. :)

But I'm up and running!

![image](https://github.com/tmaestrini/easyGovernance/assets/1295627/b27d71f3-d040-44e0-9159-a0e4d1fb4e27)

**Comment by sympmarc** [comment]
Sorry to have bothered you with trivialities.

**Comment by tmaestrini** [comment]
No worries, Marc! Anytime!
