### ISSUE TITLE
Path to awesome

### ISSUE THREAD

**Issue by sympmarc** [tmaestrini/easyGovernance#16]
I'm making updates to the README. As I'm following along, it's not clear how best to run the validator. I think what you're aiming for right now @tmaestrini is for me to edit `example-validation.ps1` or `example-validation-data.ps1`, replacing `"[tenantname].yml"` with my settings file.

The issue we have there is the same one we had in the beginning: if I edit either of those files, I'm not able to commit a PR or update my repo without overwriting those changes. Or am I missing something?

Before I commit my updates to README, I want to be sure I understand your thinking.

**Comment by tmaestrini** [comment]
Hey Marc, thanks for your question. Great that you're planning to extend the documentation! 💪💪💪

Your assumption to replace the [tenantname].yml in the example file with the file name that contains your tenant specific setting (for example sympraxis.yml).

As there's still work in progress, this leads to the "issue" that you've mentioned. 

This is how I handle it: I'm not modifying the example-validation.ps1 - instead, I'm copying the content in a local file without saving it. With that "testaround" 😂, everything runs like a charm - and no example file will be overwritten and ready to be updated in the repo. And all files in the 'tenants' folders (where you can put your tenant specific baseline setup) are not under source control.

Did this information clarify how to handle this kind of "commit-deadlock"? Have a great day! 🙌

**Comment by tmaestrini** [comment]
Thanks for this great contribution, @sympmarc. I will close this issue.
