### ISSUE TITLE
Report generation

### ISSUE THREAD

**Issue by tmaestrini** [tmaestrini/easyGovernance#18]
To get a proper overview over the services within the tenant, a function to generate a validation report (Markdown) should be implemented.

**Comment by tmaestrini** [comment]
First attempt is done – ready for a review: check out the branch '18-report-generation'.

A report can be generated very easily by taking the validation output and feed it into the `New-Report` cmdlet. First of all, a markdown file (`yyyymmmddHHmm-Report.md`) will be written in `./outputs ` directory:
```powershell
# Validate a given tenant from settings file
Import-Module .\src\Validation.psm1 -Force
$a = Start-Validation -TemplateName "tmaestrini.yml" -ReturnAsObject 

New-Report -ValidationResults $a -AsHTML
```
If you would like to generate an according HTML representation, just add the parameter `-As HTML`:
```powershell
# Validate a given tenant from settings file
Import-Module .\src\Validation.psm1 -Force
$a = Start-Validation -TemplateName "tmaestrini.yml" -ReturnAsObject 

New-Report -ValidationResults $a -AsHTML
```
You're good to go! 😉

![image](https://github.com/tmaestrini/easyGovernance/assets/69770609/01fd9766-55f4-407e-9720-f7bacf0f160c)

**Comment by tmaestrini** [comment]
@sympmarc What do you think about this?

**Comment by sympmarc** [comment]
@tmaestrini - That's beautiful! 

I haven't tried to debug it yet, but I'm getting this error:
```
Set-LoggingDefaultLevel: The term 'Set-LoggingDefaultLevel' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
```

on the line
``` powershell
$a = Start-Validation -TemplateName "sympraxis.yml" -ReturnAsObject 
```

**Comment by sympmarc** [comment]
`New-Report -ValidationResults $a` gives me an MD file containing HTML

`New-Report -ValidationResults $a -AsHTML` gives me this error. Think I'm just missing a file.

[2024-04-05 14:41:12-04] [INFO   ] Markdown report created: C:\code\Governance\easyGovernace-18-report-generation\easyGovernance\src\Public\Validation\..\..\..\output/202404051441-Report.md
Convert-MarkdownToHTML: C:\code\Governance\easyGovernace-18-report-generation\easyGovernance\src\Public\Validation\New-Report.ps1:68:24
Line |
  68 |           $htmlOutput = Convert-MarkdownToHTML $reportFilePath -SiteDi …
     |                         ~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Convert-MarkdownToHTML' is not recognized as a name of a cmdlet, function, script file, or executable        
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.     
Copy-Item: C:\code\Governance\easyGovernace-18-report-generation\easyGovernance\src\Public\Validation\New-Report.ps1:69:10    
Line |
  69 |           Copy-Item -Path (Join-Path $PSScriptRoot -ChildPath '../../. …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path
     | 'C:\code\Governance\easyGovernace-18-report-generation\easyGovernance\output\styles\md-styles.css'.

PS C:\code\Governance\easyGovernace-18-report-generation\easyGovernance> [2024-04-05 14:41:12-04] [INFO   ] HTML report created:

**Comment by sympmarc** [comment]
Needed this module:
`Install-Module -Name MarkdownToHTML`

**Comment by sympmarc** [comment]
FYI - the `settings_template.yml` file doesn't match the baselines available in \easyGovernance\baselines

**Comment by tmaestrini** [comment]
> FYI - the `settings_template.yml` file doesn't match the baselines available in \easyGovernance\baselines

Thanks for this. Didn't have it on the radar. Will fix it asap. 💪💪💪

**Comment by tmaestrini** [comment]
> Needed this module:
> 
> `Install-Module -Name MarkdownToHTML`
> 
> (as you know!)

I should add this Module as dependencies. Sorry for the poor communication on my part.

**Comment by sympmarc** [comment]
No worries. All part of testing.

Looks like you're also missing a validation ps1 for `M365.IAM-1-2.1.yml`.

**Comment by tmaestrini** [comment]
Does the mix of MD and HTML cause distraction? Id it does, we could tidy up an generste "pure" MD and write an adaptor for the HTML content.

**Comment by sympmarc** [comment]
For now, it certainly works. It's nice-looking output. Technically, it's not markdown.

**Comment by tmaestrini** [comment]
Yes, you're right. I think we should tidy it up. It's still work in progress.

But over all - do you like the "content" and the style of the presentation?

**Comment by sympmarc** [comment]
Absolutely. The output looks good and is suitable to put into a PowerPoint or to share with management.

**Comment by tmaestrini** [comment]
### ✔︎ Report generation was merged to develop and main branch

**Comment by Adam-it** [comment]
Hey @tmaestrini do you consider supporting other report types? I explain which and why
- JSON - if we have a bigger script that would automate and do something based on response from this to then parsing MD is harder then just converting output to object
- CSV - in it world there is always a need for Excel report. CSV is an easy starting point to that

**Comment by tmaestrini** [comment]
That's a great idea, @Adam-it . We will work it out and let you know. Thanks for your contribution, you're a 🚀

**Comment by tmaestrini** [comment]
New reporting options added:

```powershell
# Generate a report in directory ./output, either as .csv or .json file
New-Report -ValidationResults $result -AsCSV -AsJSON
```
