### ISSUE TITLE
Setting tenant config variables

### ISSUE THREAD

**Issue by sympmarc** [tmaestrini/easyGovernance#2]
Before you can run [Engine-BaselineValidator-M365-SPO.ps1](https://github.com/tmaestrini/easyGovernance/blob/develop/validators/Engine-BaselineValidator-M365-SPO.ps1), you need to set the tenant name for `$AdminCenterURL`. Once you do that, you get into a tangle when doing a push/pull.

This is something I used to do endlessly in my scripts. Now I have this scheme...

All I need to do is set the tenant in `settings.json` (below), and I'm off and running. Anywhere in my scripts I need a tenant URL, I can just use something like `$dstSiteName = "https://$($tenant).sharepoint.com/sites/A"`.

Would something like this make sense here? Happy to do a PR with the scaffolding if so. I expect you plan multiple validators and baselines, so this would help to make things "run ready". Since you're using YAML for the validators, we could use YAML rather than JSON for the settings file, of course.

**settings.json**
``` json
{
    "tenant": "myTenantName"
}
```

**In Engine-BaselineValidator-M365-SPO.ps1**
``` powershell
Import-Module ./utilities/UtilityFunctions.psm1 -Force

Add-SympVariables

...
```

**In UtilityFunctions.psm1**
``` powershell
<#
.Synopsis
.DESCRIPTION
.EXAMPLE
   Add-SympVariables
#>
function Add-SympVariables {
   [CmdletBinding()]
   [Alias()]
   [OutputType([int])]
   Param
   (

   )

   Begin {

      $root = ".\utilities"
      $settings = Get-Content -Path "$($root)\.settings.json" | ConvertFrom-Json

   }
   Process {

      Write-Host "Setting global variables..."

      Set-Variable -Scope global -Name tenant -Value $settings.tenant
      Set-Variable -Scope global -Name adminSiteUrl -Value "https://$($tenant)-admin.sharepoint.com"      

   }
   End {

   }
}
```

**Comment by tmaestrini** [comment]
I will dig into later on...

**Comment by tmaestrini** [comment]
I really like your suggestions in #3! Let's start with your implementation and extend it afterwords (step by step):
1. Modularization
2. Refine settings.json structure (and change to settings.yml) that even contains all baseline configs of the tenant / customer
3. Refine modules structure (according to PoSh module recommendations)
4. Implement proper validation workflow based on template

**Comment by sympmarc** [comment]
I just converted from JSON to YAML in my PR.

**Comment by sympmarc** [comment]
Now you're getting fancy. :) You probably have thought further ahead than I have. I like where you're aiming, though.

**Comment by sympmarc** [comment]
Should the baselines be in a PSM1 file, though? Shouldn't they stand alone as YAML files so people can choose from the baseline they want to use?

**Comment by tmaestrini** [comment]
> Should the baselines be in a PSM1 file, though? Shouldn't they stand alone as YAML files so people can choose from the baseline they want to use?

Exactly. In my thoughts, `Baselines.psm1` only **imports the necessary modules** for baseline management – as an example:
```powershell
$Public = @( Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -ErrorAction SilentlyContinue )
$Private = @( Get-ChildItem -Path $PSScriptRoot\Private\*.ps1 -ErrorAction SilentlyContinue )

Foreach ($import in @($Public + $Private)) {
  Try {
    . $import.fullname
  }
  Catch {
    Write-Error -Message "Failed to import function $( $import.fullname ): $_"
  }
}

Export-ModuleMember -Function $Public.Basename
```
As you say, the baseline definition remains in its own yaml-file, e.g.`baselines/M365.SPO-5.2.yml`
The settings file contains a reference to the baselines which are linked to the tenant:
```yaml
Tenant: sympraxis  # <-- I like it BTW 🤣

Baselines:
  - M365.SPO
  - M365.<Baseline1>
  - M365.<Baseline2>
  - M365.<Baseline...>
```

With this approach, you also can take the `settings.yml` and put it in a repo – as you then have your customers' setup documented "for free"😃

**Comment by sympmarc** [comment]
BTW, I didn't intend for `.settings.yml` to end up in the repo. I meant it to be excluded by .gitignore.

**Comment by tmaestrini** [comment]
I've pushed a bunch of changes on an `experimental` branch – containing a small architectural extension.
What do you think about? If you agree with my extension, I would merge them to develop and main branch.
