### ISSUE TITLE
Missing file for TEST-M365.IAM-1-2.1

### ISSUE THREAD

**Issue by stewartyork** [tmaestrini/easyGovernance#21]
When running the code I get an Error.... Seems the file is missing?

The term 'Test-M365.IAM-1-2.1' is not recognized as a name of a cmdlet, function, script file, or executable program.

@tmaestrini @dako365

**Comment by stewartyork** [comment]
[like]  Stewart York reacted to your message:
________________________________

**Comment by stewartyork** [comment]
Also the original name was still AAD versus IAM in the files and the ref failed when I tried it the first time. So I would update the file names.

**Comment by tmaestrini** [comment]
Got it, @stewartyork. Does the script execution break or do you encounter an error message while the validation script tries to test the IAM baseline? Like this:
![image](https://github.com/tmaestrini/easyGovernance/assets/69770609/c84fe9bb-0bea-46af-83fc-17b00a01f104)

**Comment by tmaestrini** [comment]
@stewartyork The issue was fixed.
Check out latest version on main branch; it also contains a new reporting engine which was discussed in #18.
Hope you'll like it! 😊

**Comment by stewartyork** [comment]
![Issue1](https://github.com/tmaestrini/easyGovernance/assets/8656522/e6c863c5-f3ae-4bdd-a926-4afd2925bbf5)

**Comment by tmaestrini** [comment]
Have you removed the M365.IAM-1-2.1 from your reference in the tenant's declaration (the tenant.yml file)?

As there's still work in progress, we have no validator pubished for this baseline. That's the cause of the error message.
