### ISSUE TITLE
powershellyaml RequirrdVersion in example-validation-report.ps1 missing 

### ISSUE THREAD

**Issue by dako365** [tmaestrini/easyGovernance#24]
Hi Toby

if you run the script example-validation-report.ps1, the "requiredversion" is missing in the output for "powershellyaml".

![screenshot_example-validation-report ps1](https://github.com/tmaestrini/easyGovernance/assets/152610222/ce29eaed-edbd-474a-b6cc-c61a6dc80305)

**Comment by tmaestrini** [comment]
@dako365 Issue is fixed. Because module dependencies without version binding can exist, I've implemented an appropriate handling. See commit above.
