### ISSUE TITLE
`settings_template.yml` vs. `baselines` files

### ISSUE THREAD

**Issue by sympmarc** [tmaestrini/easyGovernance#34]
The baselines listed in `settings_template.yml` don't match the filenames in the `baselines` folder. I still think getting up and running is a bit confusing - and I'm a good guinea pig for that.

Is it the intention that if the filenames in the `baselines` folder change, then they should also change in `settings_template.yml`? The ps1 files like `src\Private\Validation\Test-M365.1-1.1.ps1` also seem to have to match the `baselines` filenames. It feels a bit brittle to me.

**Comment by tmaestrini** [comment]
@sympmarc Thanks for your contribution!
The filenames in the `baselines` folder don't match the references in the tenant settings file (`settings_template.yml`). As you've described, this could lead to confusion.

For now, there are two options to reference a baseline from the tenant settings file:
1. By referencing its filename (aka the "name" of the file without `.yml` suffix); e.g. `M365.IAM.1-2.1`
2. By referencing its `id` which is contained in the baseline; e.g. `M365.1-2.1`

It doesn't matter which option you choose.

But to make it clearer from an end user perspective, I think we should add this to the documentation here:
https://github.com/tmaestrini/easyGovernance#tenant-settings-file

**Comment by tmaestrini** [comment]
@sympmarc My bad – you were right: the reference must match filename of the `.yml` file in the `baselines` folder (or wherever you set the reference to). Therefore, I've changed the definitions in the `settings_template.yml`.
Hoping that the confused guinea pig now is eating green grass again... 😃

**Comment by sympmarc** [comment]
🐹
![GrassGIF](https://github.com/tmaestrini/easyGovernance/assets/1295627/7b49835c-a9c8-4a38-9e38-11812f22b8b6)
