### ISSUE TITLE
Baseline `M365.1-1.1` errors 

### ISSUE THREAD

**Issue by sympmarc** [tmaestrini/easyGovernance#40]
When validating with baseline `M365.1-1.1`, consistent errors for parameter checks. This is after successful connections.
![image](https://github.com/tmaestrini/easyGovernance/assets/1295627/50858962-c925-433b-bdab-c14b2e2f9c7e)

**Comment by tmaestrini** [comment]
I think this error is connected to #39

**Comment by sympmarc** [comment]
Agreed. I just wanted to record it separately.

I'm debugging, and if I stop at the connection line and just retry until it works (maybe 1 / 10 tries), then I can proceed. 

I've introduced a retry in `M365AdminCenter.psm1`, which helps, but doesn't solve the problem - yet.
``` powershell
        try {
            # $path = ($req.path) -replace "{{tenantId}}", $tenantId
            $path = "https://admin.microsoft.com/$($req.path)"
            $method = $($req.method) ? $req.method : "GET"
            $result = Invoke-RestMethod -Uri $path -Headers $headers -Method "$($method)" -RetryIntervalSec 5
            $propertiesValues | Add-Member -MemberType NoteProperty -Name $req.name -Value ($req.attr ? $result.$($req.attr) : $result)
        }
```

**Comment by tmaestrini** [comment]
Any updates on this, @sympmarc – or did this error disappear?
As we had to implement new authentication mechanism in #41 due to PnP.PowerShell security redesign, i'd be interested to know if the issue is still occurring?

**Comment by sympmarc** [comment]
I just ran a validation with the latest code and I don't see any errors:

![image](https://github.com/user-attachments/assets/61aa75a0-c120-45d7-9f64-48ef078a34a2)
