### ISSUE TITLE
Adjustments according to PnP.PowerShell interactive login changes

### ISSUE THREAD

**Issue by tmaestrini** [tmaestrini/easyGovernance#41]
As of September 9th, 2024, s part of a focus on improving the security posture, the multi-tenant PnP Management Shell EntraID app for PnP.PowerShell has been deleted.

Therefore, the authentication flow in PnP.PowerShell have to be adjusted in every tenant. This impacts the credentials flow, interactive flow as well as device login flow , only if you used this app.

As easyGovernance uses PnP.PowerShell as a core module, the setup has to be adjusted.

**Comment by tmaestrini** [comment]
@sympmarc I will adjust the whole underlying authentication mechanism. Would you be fine to write a short "installation guideline" afterwords and reference it from the README.md?

**Comment by sympmarc** [comment]
Ideally, we would link to the PnP.PowerShell explanation for settings things up so we don't reinvent the wheel. That said, I think we've been sort of assuming that people have PnP.PowerShell available and running. On most levels, I see that as acceptable. You?

What changes to the underlying auth mechanisms are you thinking?

**Comment by tmaestrini** [comment]
> That said, I think we've been sort of assuming that people have PnP.PowerShell available and running. On most levels, I see that as acceptable. You?

Yes, @sympmarc – good point! But the easy-going "interactive" login method needs a client id that points to the PnP-related app registration in your Azure tenant. Therefore, I've already implemented the adoption to the new authentication mechanism – in order to make the use of the tool as "easy" as possible... 😄  

It's very straightforward: first of all, it checks if an "easyGovernance" app registration is in your tenant. If not, the app registration for "easyGovernance" will be created – if the app exists, then ok. After that the according app id will be returned and passed to the Connect-PnPOnline routine. That's it! 😄 It also works in unattended mode.

That said, we should provide a minimum of documentation to the user, with – as you said – linking the topic to the official PnP.PowerShell docs. But I think it would be good style to let the user know what's going on in his Azure tenant when he starts easyGovernance for the first time. What do you think?

**Comment by tmaestrini** [comment]
Branch `41-authentication-pnp` was merged into develo
