### ISSUE TITLE
Improve the documentation on what is meant by "tenant"

### ISSUE THREAD

**Issue by Tanddant** [tmaestrini/easyGovernance#46]
From the readme: 
>Tenant settings file
In order to configure a dedicated baseline configuration for a specific tenant, an according tenant settings file must be created (yml). The file name can be chosen according to your needs (ending with .yml); consider using the tenant's name as the file descriptor, e.g. [tenantname.yml].

I initially went with "Tenant.onmicrosoft.com" - which caused an attempted connection to "Tenant.onmicrosoft.com.onmicrosoft.com" - perhaps we should just validate if the tenant name contains a . and if it does, just trust that it's a valid tenant URI

**Comment by tmaestrini** [comment]
Thanks for this suggestion. You're right, but when we talk about the tenant's name, we refer to the `<tenantname>` before the `.onmicrosoft.com` or `.sharepoint.com`.

To make it clear and to avoid common misunderstandings, we could do these things:

1. adjust / extend the documentation with an example that covers the above explanation
2. implement a validation check according to your suggestion

Anyone interested in doing this?

**Comment by Tanddant** [comment]
I found out ... this might also just be a case of me being hungover from a wine tasting 😅

I'm happy to just extend the documentation, I have a feeling we wouldn't be able to make a bulletproof validation anyway, dumb dumbs like myself will always find a way to break it, feel free to assign me this issue 👍

**Comment by tmaestrini** [comment]
All yours!

**Comment by Tanddant** [comment]
I've done a basic attempt over here, do you mind taking a look at if it makes more sense before I open a PR?

https://github.com/Tanddant/easyGovernance/commit/92e80a38e8dc607e8d8a871c94ffb48d7d16bba8

**Comment by tmaestrini** [comment]
> I've done a basic attempt over here, do you mind taking a look at if it makes more sense before I open a PR?

You're awesome. Go, go, go... 👍
